### ISSUE TITLE
Is this tool relevant anymore?

### ISSUE THREAD

**Issue by mahozad** [fwilhe2/setup-kotlin#174]
Now that GitHub actions environments have Kotlin pre-installed ([issue](https://github.com/actions/virtual-environments/issues/3687), [YouTube announcement](https://youtu.be/etEJv1rb8HI?t=263)), do I need this tool anymore in my actions?

**Comment by fwilhe2** [comment]
Hi @mahozad 

I've seen that GitHub added Kotlin to the runner environments, and I think that's a great change.

I think there are still some cases where this action provides additional benefit.

For example if you want to make use of the Kotlin native compiler, or if you want to chose a specific Kotlin version, or if your Workflow runs inside a Container or Self-Hosted runner.

But overall I think for most users you are probably right that this action has been replaced with a better solution, so if you don't need it anymore, I encourage you to remove it from your workflows.

Kind regards

Florian

**Comment by fwilhe2** [comment]
I've updated the hint in the readme, I hope that helps people to judge if the action is useful to them.

![Screenshot from 2021-09-07 21-49-08](https://user-images.githubusercontent.com/52838694/132402614-eedb1555-1891-46d7-a269-f53966b6f5fa.png)

Please let me know if you have any suggestions for writing this more clearly.

**Comment by mahozad** [comment]
@fwilhe2 That's good. Thank you.

**Comment by JavierSegoviaCordoba** [comment]
Built in solution doesn’t allow inline scripts no?

**Comment by JavierSegoviaCordoba** [comment]
Do you know a tutorial about how to migrate from bash to kotlin the typical things like setting an output and so on?

**Comment by christianhujer** [comment]
Is this tool still relevant? I don't know, maybe. I just used this despite Kotlin being available on GitHub actions out of the box because I needed Kotlin 1.6.0 and the GitHub actions only had 1.5.31. And I couldn't figure out how to tell GitHub actions to use Kotlin 1.6.0 instead of 1.5.31 in any other way than using this tool.
