### ISSUE TITLE
Un Resolved Import

### ISSUE THREAD

**Issue by amirisback** [fwilhe2/setup-kotlin#274]
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/24654871/198813742-806e5cf1-59b7-415a-806d-22904e219365.png">

## Link
https://github.com/amirisback/caravan-kotlin/actions/runs/3350039027/jobs/5550566369

## Issue
Why when Class import method / function from another files always failed in github action with error unresolved reference?

**Comment by fwilhe2** [comment]
Hi @amirisback 

I currently don't have time to look into this issue, but my impression is that using my action is not the best solution for your issue. I'd recommend to follow this guide: [Get started with Kotlin/Native using Gradle](https://kotlinlang.org/docs/native-gradle.html). You won't need the setup-kotlin action when gradle takes care of that.

**Comment by amirisback** [comment]
thank you very much, now i using gradle task for automation in github action
