### ISSUE TITLE
`Error: Unexpected HTTP response: 404` when using Kotlin 1.9.20

### ISSUE THREAD

**Issue by christianhujer** [fwilhe2/setup-kotlin#406]
```
Run fwilhe2/setup-kotlin@main
  with:
    version: 1.9.[2](https://github.com/nelkinda/monitor/actions/runs/6707651425/job/18227602876#step:4:2)0
    install-native: false
  env:
    JAVA_HOME: /opt/hostedtoolcache/Java_Zulu_jdk/20.0.2-9/x6[4](https://github.com/nelkinda/monitor/actions/runs/6707651425/job/18227602876#step:4:4)
    JAVA_HOME_20_X[6](https://github.com/nelkinda/monitor/actions/runs/6707651425/job/18227602876#step:4:6)4: /opt/hostedtoolcache/Java_Zulu_jdk/20.0.2-9/x64
Error: Unexpected HTTP response: 404
```

**Comment by fwilhe2** [comment]
Hi @christianhujer 

seems like kotlin 1.9.20 is not out yet, I can only see RC versions [here](https://github.com/JetBrains/kotlin/releases).

Using the RC2 seems to work as demonstrated [here](https://github.com/fwilhe2/improved-enigma/actions/runs/6710029136/job/18234351884)

To be fair, the urls had been unstable in the past, so I would not be too surprised if this broke again in the future, but it seems to be working with most recent versions of of now.

Out of curiosity, would you mind telling me about your use-case of this action? I feel the actual use-cases where this action makes sense is very narrow, so I'm always a bit surprised when someone seems to be actively using it.

Note that Github has added kotlin to [the default runner images as far as I'm aware of](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md#language-and-runtime).

Best,
Florian
