### ISSUE TITLE
Version scheme

### ISSUE THREAD

**Issue by LouisCAD** [fwilhe2/setup-kotlin#83]
Hello,
What are the reasons this project doesn't match the Kotlin versioning scheme?

**Comment by fwilhe2** [comment]
Hi @LouisCAD,

just to be sure I understand what you mean:

Action with version 1.4.20 should match to Kotlin compiler version 1.4.20?

Not sure about that. What would be the benefits?

I assume people will want to use latest version most of the time, and other versions can be selected using [version](https://github.com/fwilhe2/setup-kotlin/blob/main/action.yml#L8) option.

On the downside, the action would create lots of versions for each new Kotlin release where nothing really changes. And how would I release actual changes of code in the action? Say the current version is 1.4.20, and I built a new feature into the action, what would be the right version assuming no new kotlin release exists?

Maybe I did not understand what you're asking for correctly. Mind to elaborate a bit?
