### ISSUE TITLE
Error: Unexpected HTTP response: 404

### ISSUE THREAD

**Issue by elbaulp** [fwilhe2/setup-kotlin#97]
Hello, I am getting the following error when running the action as this:

```
    - name: Set up Kotlin
      uses: fwilhe2/setup-kotlin@main
```

```
Run fwilhe2/setup-kotlin@main
  with:
    version: 1.4.30
    install-native: true
  env:
    ARTIFACTORY_PASS: ***
    ARTIFACTORY_USER: ***
/usr/bin/unzip -q /home/runner/work/_temp/18389baf-d687-42a3-8679-43748467e449
Error: Unexpected HTTP response: 404
```

**Comment by fwilhe2** [comment]
Hi @elbaulp 

thanks for reporting. Seems like jetbrains changed the url schema for kotlin/native for the second time. Not sure why.

If you don't want/need kotlin native (i.e. if you want to use the jvm or js compiler) you can set `install-native` to false.

Not sure how to fix this. I can update the url again, but not sure when jetbrains will change it again. Maybe `install-native` should be false by default.

**Comment by fwilhe2** [comment]
Should be resolved in `main` and https://github.com/fwilhe2/setup-kotlin/releases/tag/0.2.0

Note that in case you want kotlin native, this has to be enabled now.

**Comment by elbaulp** [comment]
Thank you very much!
